### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [laytya/EQL3#9]
[2018/02/03 19:25:38-1990]: core\tooltip.lua:26: Invalid quest item in SetQuestLogItem("type", index)
<in C code>: in function `?'
core\tooltip.lua:26: in function <Interface\AddOns\aux-addon\core\tooltip.lua:23>
<unknown>:
<string>:"EQL3_QuestLogItem1:OnEnter":4: in main chunk

  ---

**Comment by laytya** [comment]
its aux error not EQL
